### ISSUE TITLE
Can start, get Unhandled Exception

### ISSUE THREAD

**Issue by ForceConstant** [xantari/PinCabScreenConfigurator#2]
Stumbled upon this app, which seems useful, but can't start it. 

```
2020-07-13 10:51:14.057 -04:00 [INF] Application Started. Version: 1.0.7499.19285
2020-07-13 10:51:14.973 -04:00 [ERR] Unhandled Exception occurred. System.NullReferenceException: Object reference not set to an instance of an object.
   at PinCab.ScreenUtil.DisplayDetailsExtensions.<>c.<ValidateDisplayConfiguration>b__8_1(DisplayDetail p) in C:\Users\myuser\Downloads\PinCabScreenConfigurator-master\PinCab.ScreenUtil\Extensions\DisplayDetailsExtensions.cs:line 162
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PinCab.ScreenUtil.DisplayDetailsExtensions.ValidateDisplayConfiguration(List`1 displayDetails) in C:\Users\myuser\Downloads\PinCabScreenConfigurator-master\PinCab.ScreenUtil\Extensions\DisplayDetailsExtensions.cs:line 162
   at PinCab.Configurator.MainForm.ValidateMonitorConfiguration() in C:\Users\myuser\Downloads\PinCabScreenConfigurator-master\PinCab.Configurator\MainForm.cs:line 141
   at PinCab.Configurator.MainForm..ctor() in C:\Users\myuser\Downloads\PinCabScreenConfigurator-master\PinCab.Configurator\MainForm.cs:line 55
   at PinCab.Configurator.Program.Main() in C:\Users\myuser\Downloads\PinCabScreenConfigurator-master\PinCab.Configurator\Program.cs:line 36
```

**Comment by xantari** [comment]
Looks like it might happen when you haven't assigned any screens yet. This is still a WIP. Try assign a screen such as the playfield before running validate to see if that fixes it. Will have to put in additional checks around this whenever I can get time to finishing this program up.

**Comment by xantari** [comment]
@ForceConstant Sorry for delay in this. I started working on this again.

Can you see if you get the same issue with 0.1.30 version?

**Comment by xantari** [comment]
@ForceConstant Sorry, it seems my auto build/deploy pipeline has been broken for awhile, so the latest versions weren't being deployed with the compiled binaries. Try the 0.1.132 release.

**Comment by xantari** [comment]
Closing due to inactivity...
